name: Main

on:
  push:
  schedule:
    - cron: "0,20,40 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch
        run: |
          curl "https://api.github.com/users/christianbundy/repos?per_page=100&page=1" | jq '.[].name' | xargs -L 1 -P $(nproc) -I {} git clone --depth=1 --filter=blob:none --no-checkout git://github.com/christianbundy/{}.git {} || true

          curl "https://api.github.com/users/christianbundy/repos?per_page=100&page=2" | jq '.[].name' | xargs -L 1 -P $(nproc) -I {} git clone --depth=1 --filter=blob:none --no-checkout git://github.com/christianbundy/{}.git {} || true

          curl "https://api.github.com/users/christianbundy/repos?per_page=100&page=3" | jq '.[].name' | xargs -L 1 -P $(nproc) -I {} git clone --depth=1 --filter=blob:none --no-checkout git://github.com/christianbundy/{}.git {} || true

          curl "https://api.github.com/users/christianbundy/repos?per_page=100&page=4" | jq '.[].name' | xargs -L 1 -P $(nproc) -I {} git clone --depth=1 --filter=blob:none --no-checkout git://github.com/christianbundy/{}.git {} || true

      - name: Commit
        run: |
          for f in *; do
              git submodule add git://github.com/christianbundy/{}.git {} || true;
          done
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
